### ISSUE TITLE
TypeError: output[i].author is not a function

### ISSUE THREAD

**Issue by alanshaw** [juliangruber/git-log#2]
I seem to be getting this error on repos I cloned a while ago. Cloning the same repo fresh resolves the issue...

```sh
/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-walk-refs/index.js:77
        _human = output[i].human = human(output[i].author() || output[i].commi
                                                   ^
TypeError: output[i].author is not a function
    at done (/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-walk-refs/index.js:77:52)
    at /Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-walk-refs/index.js:52:25
    at /Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-fs-repo/index.js:64:5
    at got (/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-fs-repo/node_modules/git-odb/index.js:62:14)
    at Stream.<anonymous> (/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-fs-repo/node_modules/git-odb-loose/index.js:40:35)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at drain (/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-fs-repo/node_modules/through/index.js:35:16)
    at Stream.stream.queue.stream.push (/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-fs-repo/node_modules/through/index.js:41:5)
    at done (/Users/alan/Code/fun/git-days/node_modules/git-log/node_modules/git-fs-repo/node_modules/git-odb-loose/parse.js:40:12)
```

**Comment by juliangruber** [comment]
would you be willing to dig into this issue a little? i'm short on time atm

**Comment by alanshaw** [comment]
It's failing when `output[i]` is a 'git-object-tag'.

Tags don't have "authors" or "committers" they have taggers.

Now failing a little later in the code when asking the tag for "parents". Hopefully PR soon.
